import type { Database } from "@/lib/types";

export function createSeed(): Database {
  const customers = [
    {
      id: "cus_nusantara",
      name: "PT Nusantara Konstruksi",
      pic: "Budi Santoso",
      phone: "021-555-1100",
      email: "pengadaan@nusantara.co.id",
      address: "Jl. Gatot Subroto No. 88, Jakarta Selatan",
      npwp: "10.0.1.3-012.000",
      notes: "Kontrak banner proyek 2026, harga khusus volume.",
      createdAt: "2026-01-12T08:00:00.000Z",
    },
    {
      id: "cus_dinas",
      name: "Dinas Pendidikan Kota",
      pic: "Ibu Rina Wulandari",
      phone: "021-555-2200",
      email: "umum@disdik.kota.go.id",
      address: "Komplek Perkantoran Kota, Blok A Lt. 3",
      npwp: "00.0.0.1-000.000",
      notes: "Pengadaan berkala ATK dan undangan resmi.",
      createdAt: "2026-02-03T08:00:00.000Z",
    },
    {
      id: "cus_sinar",
      name: "CV Sinar Abadi Retail",
      pic: "Andi Wijaya",
      phone: "0812-3300-4411",
      email: "andi@sinarabadi.id",
      address: "Jl. Raya Darmo No. 12, Surabaya",
      npwp: "10.10.0.4-608.000",
      notes: "Langganan kertas dan brosur promo toko.",
      createdAt: "2026-03-18T08:00:00.000Z",
    },
    {
      id: "cus_rs",
      name: "RS Sehat Medika",
      pic: "dr. Maya Putri",
      phone: "031-8890-221",
      email: "humas@sehatmedika.id",
      address: "Jl. Ahmad Yani No. 45, Surabaya",
      npwp: "192.168.2.3-608.000",
      notes: "Kartu nama dokter dan stempel unit.",
      createdAt: "2026-04-09T08:00:00.000Z",
    },
  ];

  const products = [
    {
      id: "prd_banner",
      sku: "PRC-BAN-280",
      name: "Banner Flexy 280gsm",
      category: "percetakan" as const,
      unit: "m2",
      stock: 86,
      minStock: 30,
      costPrice: 18000,
      defaultPrice: 45000,
      trackStock: true,
      description: "Outdoor, finishing mata ayam sesuai request.",
      createdAt: "2026-01-08T08:00:00.000Z",
    },
    {
      id: "prd_spanduk",
      sku: "PRC-SPN-KAIN",
      name: "Spanduk Kain",
      category: "percetakan" as const,
      unit: "m2",
      stock: 80,
      minStock: 20,
      costPrice: 12000,
      defaultPrice: 30000,
      trackStock: true,
      description: "Kain polyester, sablon atau digital.",
      createdAt: "2026-01-08T08:00:00.000Z",
    },
    {
      id: "prd_kartu",
      sku: "PRC-KN-ART",
      name: "Kartu Nama Art Carton",
      category: "percetakan" as const,
      unit: "box",
      stock: 36,
      minStock: 10,
      costPrice: 25000,
      defaultPrice: 65000,
      trackStock: true,
      description: "1 box isi 100 pcs, laminasi doff/glossy.",
      createdAt: "2026-01-08T08:00:00.000Z",
    },
    {
      id: "prd_kop",
      sku: "PRC-KOP-A4",
      name: "Kop Surat A4",
      category: "percetakan" as const,
      unit: "rim",
      stock: 25,
      minStock: 8,
      costPrice: 45000,
      defaultPrice: 85000,
      trackStock: true,
      description: "HVS 80gr, full color header.",
      createdAt: "2026-01-08T08:00:00.000Z",
    },
    {
      id: "prd_brosur",
      sku: "PRC-BRO-A4",
      name: "Brosur A4 Art Paper",
      category: "percetakan" as const,
      unit: "rim",
      stock: 15,
      minStock: 5,
      costPrice: 55000,
      defaultPrice: 120000,
      trackStock: true,
      description: "Art paper 120gr, bolak-balik.",
      createdAt: "2026-01-08T08:00:00.000Z",
    },
    {
      id: "prd_stempel",
      sku: "PRC-STM-FL",
      name: "Stempel Flash",
      category: "jasa" as const,
      unit: "pcs",
      stock: 8,
      minStock: 3,
      costPrice: 35000,
      defaultPrice: 85000,
      trackStock: true,
      description: "Stempel flash custom ukuran standar.",
      createdAt: "2026-01-08T08:00:00.000Z",
    },
    {
      id: "prd_hvs",
      sku: "PGD-HVS-70",
      name: "Kertas HVS 70gr A4",
      category: "pengadaan" as const,
      unit: "rim",
      stock: 55,
      minStock: 20,
      costPrice: 43000,
      defaultPrice: 55000,
      trackStock: true,
      description: "Pengadaan ATK kantor, 1 rim 500 lembar.",
      createdAt: "2026-01-08T08:00:00.000Z",
    },
    {
      id: "prd_toner",
      sku: "ATK-TNR-HP",
      name: "Tinta Toner HP",
      category: "atk" as const,
      unit: "pcs",
      stock: 8,
      minStock: 4,
      costPrice: 280000,
      defaultPrice: 450000,
      trackStock: true,
      description: "Compatible HP LaserJet.",
      createdAt: "2026-01-08T08:00:00.000Z",
    },
  ];

  return {
    profile: {
      name: "CV Rizky Percetakan & Pengadaan",
      tagline: "Percetakan, ATK, dan pengadaan barang kantor",
      owner: "Rizki",
      ownerTitle: "Direktur",
      address: "Jl. Industri Raya No. 17",
      city: "Sidoarjo, Jawa Timur",
      phone: "031-8912-334",
      email: "halo@cvrizky.id",
      npwp: "10.0.0.1-643.000",
      bankName: "BCA",
      bankAccount: "1234567890",
      bankHolder: "CV Rizky",
      defaultPpnRate: 0.11,
      openingCash: 15_000_000,
      openingCapital: 28_000_000,
    },
    banks: [
      {
        id: "bnk_bca",
        bankName: "BCA",
        accountNumber: "1234567890",
        holder: "CV Rizky",
        isDefault: true,
        notes: "Rekening operasional",
      },
    ],
    customers,
    products,
    customerPrices: [
      {
        id: "price_banner_nusantara",
        customerId: "cus_nusantara",
        productId: "prd_banner",
        unitPrice: 40000,
        notes: "Harga kontrak proyek 2026",
      },
      {
        id: "price_banner_dinas",
        customerId: "cus_dinas",
        productId: "prd_banner",
        unitPrice: 55000,
        notes: "Harga pengadaan instansi",
      },
      {
        id: "price_hvs_sinar",
        customerId: "cus_sinar",
        productId: "prd_hvs",
        unitPrice: 50000,
        notes: "Harga volume ritel",
      },
      {
        id: "price_kartu_rs",
        customerId: "cus_rs",
        productId: "prd_kartu",
        unitPrice: 70000,
        notes: "Termasuk desain nama dokter",
      },
    ],
    orders: [
      {
        id: "ord_1",
        number: "ORD/2026/09/0001",
        customerId: "cus_nusantara",
        date: "2026-09-12",
        dueDate: "2026-09-20",
        status: "proses",
        notes: "Banner locsheed proyek Gatot Subroto, finishing mata ayam 4 sudut.",
        items: [
          {
            id: "ord_1_i1",
            productId: "prd_banner",
            name: "Banner Flexy 280gsm",
            spec: "3 x 8 m, 1 sisi, mata ayam",
            qty: 24,
            unit: "m2",
            unitPrice: 40000,
            costPrice: 18000,
          },
        ],
        createdAt: "2026-09-12T09:10:00.000Z",
      },
      {
        id: "ord_2",
        number: "ORD/2026/09/0002",
        customerId: "cus_dinas",
        date: "2026-09-16",
        dueDate: "2026-09-25",
        status: "baru",
        notes: "Undangan rapat dinas + kop surat semester 2.",
        items: [
          {
            id: "ord_2_i1",
            productId: "prd_kop",
            name: "Kop Surat A4",
            spec: "Header full color, HVS 80gr",
            qty: 10,
            unit: "rim",
            unitPrice: 85000,
            costPrice: 45000,
          },
          {
            id: "ord_2_i2",
            productId: "prd_kartu",
            name: "Kartu Nama Art Carton",
            spec: "Pejabat dinas, 1 box / orang",
            qty: 6,
            unit: "box",
            unitPrice: 65000,
            costPrice: 25000,
          },
        ],
        createdAt: "2026-09-16T11:40:00.000Z",
      },
    ],
    invoices: [
      {
        id: "inv_1",
        number: "INV/2026/09/0001",
        fakturNumber: "FKT/2026/09/0001",
        orderId: null,
        customerId: "cus_rs",
        date: "2026-09-05",
        dueDate: "2026-09-19",
        status: "terbit",
        items: [
          {
            id: "inv_1_i1",
            productId: "prd_kartu",
            name: "Kartu Nama Art Carton",
            spec: "Dokter spesialis, laminasi doff",
            qty: 4,
            unit: "box",
            unitPrice: 70000,
            costPrice: 25000,
          },
          {
            id: "inv_1_i2",
            productId: "prd_stempel",
            name: "Stempel Flash",
            spec: "Unit IGD dan farmasi",
            qty: 2,
            unit: "pcs",
            unitPrice: 85000,
            costPrice: 35000,
          },
        ],
        discount: 0,
        includePpn: true,
        ppnRate: 0.11,
        notes: "Pembayaran transfer ke BCA a.n. CV Rizky.",
        bankId: "bnk_bca",
        paidAmount: 0,
        issuedAt: "2026-09-05T10:00:00.000Z",
        createdAt: "2026-09-05T09:30:00.000Z",
      },
      {
        id: "inv_2",
        number: "INV/2026/09/0002",
        fakturNumber: "FKT/2026/09/0002",
        orderId: null,
        customerId: "cus_sinar",
        date: "2026-09-08",
        dueDate: "2026-09-15",
        status: "lunas",
        items: [
          {
            id: "inv_2_i1",
            productId: "prd_hvs",
            name: "Kertas HVS 70gr A4",
            spec: "Sinarworld, 70gr",
            qty: 25,
            unit: "rim",
            unitPrice: 50000,
            costPrice: 43000,
          },
        ],
        discount: 0,
        includePpn: false,
        ppnRate: 0.11,
        notes: "Harga khusus volume ritel.",
        bankId: "bnk_bca",
        paidAmount: 1_250_000,
        issuedAt: "2026-09-08T14:00:00.000Z",
        createdAt: "2026-09-08T13:20:00.000Z",
      },
    ],
    beritaAcaras: [
      {
        id: "ba_1",
        number: "BA/2026/09/0001",
        invoiceId: "inv_2",
        orderId: null,
        customerId: "cus_sinar",
        date: "2026-09-09",
        location: "Gudang CV Sinar Abadi, Surabaya",
        title: "Berita Acara Serah Terima",
        description: "",
        items: [
          {
            id: "ba_1_i1",
            name: "Kertas HVS 70gr A4",
            spec: "Sinarworld, 70gr",
            qty: 25,
            unit: "rim",
            condition: "Baik, segel utuh",
          },
        ],
        notes: "Diterima oleh bagian gudang.",
        createdAt: "2026-09-09T08:00:00.000Z",
      },
      {
        id: "ba_2",
        number: "BA/2026/09/0002",
        invoiceId: "inv_1",
        orderId: null,
        customerId: "cus_rs",
        date: "2026-09-05",
        location: "Jl. Ahmad Yani No. 45, Surabaya",
        title: "Berita Acara Serah Terima",
        description: "",
        items: [
          {
            id: "ba_2_i1",
            name: "Kartu Nama Art Carton",
            spec: "Dokter spesialis, laminasi doff",
            qty: 4,
            unit: "box",
            condition: "Baik dan lengkap",
          },
          {
            id: "ba_2_i2",
            name: "Stempel Flash",
            spec: "Unit IGD dan farmasi",
            qty: 2,
            unit: "pcs",
            condition: "Baik dan lengkap",
          },
        ],
        notes: "",
        createdAt: "2026-09-05T11:00:00.000Z",
      },
    ],
    suratJalans: [
      {
        id: "sj_1",
        number: "SJ/2026/09/0001",
        invoiceId: "inv_2",
        orderId: null,
        customerId: "cus_sinar",
        date: "2026-09-09",
        destination: "Gudang CV Sinar Abadi, Jl. Raya Darmo No. 12, Surabaya",
        vehicle: "L 1234 XY",
        driver: "Sutrisno",
        items: [
          {
            id: "sj_1_i1",
            name: "Kertas HVS 70gr A4",
            spec: "Sinarworld, 70gr",
            qty: 25,
            unit: "rim",
            notes: "Segel utuh",
          },
        ],
        notes: "Mohon dicocokkan dengan invoice INV/2026/09/0002.",
        createdAt: "2026-09-09T07:30:00.000Z",
      },
    ],
    quotations: [],
    purchases: [
      {
        id: "pur_1",
        number: "PBL/2026/09/0001",
        date: "2026-09-02",
        supplier: "PT Flexindo Bahan",
        items: [
          {
            productId: "prd_banner",
            name: "Banner Flexy 280gsm",
            qty: 50,
            unit: "m2",
            unitCost: 18000,
          },
        ],
        paid: true,
        notes: "Restok bahan banner.",
        createdAt: "2026-09-02T08:00:00.000Z",
      },
      {
        id: "pur_2",
        number: "PBL/2026/09/0002",
        date: "2026-09-03",
        supplier: "CV Kertas Jaya",
        items: [
          {
            productId: "prd_hvs",
            name: "Kertas HVS 70gr A4",
            qty: 20,
            unit: "rim",
            unitCost: 43000,
          },
        ],
        paid: true,
        notes: "Restok HVS.",
        createdAt: "2026-09-03T08:00:00.000Z",
      },
    ],
    expenses: [
      {
        id: "exp_1",
        date: "2026-09-01",
        category: "sewa",
        description: "Sewa tempat usaha September",
        amount: 2_500_000,
      },
      {
        id: "exp_2",
        date: "2026-09-07",
        category: "utilitas",
        description: "Listrik dan air",
        amount: 450_000,
      },
      {
        id: "exp_3",
        date: "2026-09-10",
        category: "gaji",
        description: "Gaji operator dan admin",
        amount: 3_000_000,
      },
    ],
    payments: [
      {
        id: "pay_1",
        invoiceId: "inv_2",
        date: "2026-09-10",
        amount: 1_250_000,
        method: "transfer",
        notes: "Pelunasan HVS CV Sinar Abadi",
      },
    ],
    stockMoves: [
      {
        id: "sm_1",
        productId: "prd_banner",
        type: "masuk",
        qty: 50,
        unitCost: 18000,
        refType: "pembelian",
        refId: "pur_1",
        notes: "Restok bahan banner",
        date: "2026-09-02",
      },
      {
        id: "sm_2",
        productId: "prd_hvs",
        type: "masuk",
        qty: 20,
        unitCost: 43000,
        refType: "pembelian",
        refId: "pur_2",
        notes: "Restok HVS",
        date: "2026-09-03",
      },
      {
        id: "sm_3",
        productId: "prd_kartu",
        type: "keluar",
        qty: 4,
        unitCost: 25000,
        refType: "invoice",
        refId: "inv_1",
        notes: "Penjualan kartu nama RS",
        date: "2026-09-05",
      },
      {
        id: "sm_4",
        productId: "prd_stempel",
        type: "keluar",
        qty: 2,
        unitCost: 35000,
        refType: "invoice",
        refId: "inv_1",
        notes: "Penjualan stempel RS",
        date: "2026-09-05",
      },
      {
        id: "sm_5",
        productId: "prd_hvs",
        type: "keluar",
        qty: 25,
        unitCost: 43000,
        refType: "invoice",
        refId: "inv_2",
        notes: "Penjualan HVS Sinar Abadi",
        date: "2026-09-08",
      },
    ],
  };
}
